name: Agendador de Emails

on:
  schedule:
    - cron: '39 10 * * *' # Executa todos os dias às 10:37 UTC

  workflow_dispatch: # Permite execução manual

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Acessando o site e enviando email
        run: |
          echo "Chamando a URL agora..."
          curl -v -X POST \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            "http://busines.ct.ws/enviaremail.php"
          echo "Chamada finalizada"
