name: Agendador de Emails

on:
  schedule:
    - cron: '0 12 * * *' # Executa todos os dias ao meio-dia (UTC)

  workflow_dispatch: # Permite execução manual

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Acessando o site e enviando email
        run: curl -X POST "https://seusite.com/enviar-email.php"
